CREATE DATABASE raceday
USE [raceday]

CREATE TABLE Roles (
    id INT IDENTITY(1,1) CONSTRAINT PK_Roles PRIMARY KEY,
    role_name VARCHAR(50) NOT NULL CONSTRAINT UQ_Roles_Name UNIQUE
);

CREATE TABLE Users (
    id INT IDENTITY(1,1) CONSTRAINT PK_Users PRIMARY KEY,
    username VARCHAR(100) NOT NULL CONSTRAINT UQ_Users_Username UNIQUE,
    email VARCHAR(255) NOT NULL CONSTRAINT UQ_Users_Email UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role_id INT NOT NULL,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    profile_picture_url VARCHAR(2048) NULL,
    created_at DATETIME NOT NULL CONSTRAINT DF_Users_CreatedAt DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_Users_Roles FOREIGN KEY (role_id) REFERENCES Roles(id) ON DELETE NO ACTION
);
